name: cpp-linter
on:
  pull_request:
    branches: main
    paths: ['**.cpp', '**.h', '**CMakeLists.txt']
  push:
    branches: main
    paths: ['**.cpp', '**.h', '**CMakeLists.txt']

permissions:
    contents: write
    pull-requests: write
    actions: write

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'  # Use .clang-format config file. 
          tidy-checks: '-*' # disable clang-tidy checks. 
          thread-comments: true
          format-review: true

      - name: Run clang-format
        if: steps.linter.outputs.clang-format-checks-failed > 0
        run: exit 1
